server.port: 8080

spring:
  application:
    name: ${NAIS_APP_NAME:familie-ba-infotrygd}
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    platform: ${APP_DATASOURCE_PLATFORM}
    driver-class-name: ${APP_DATASOURCE_DRIVER}
  jpa:
    # For Oracle: database-platform: org.hibernate.dialect.Oracle10gDialect
    database-platform: ${APP_JPA_PLATFORM}
    hibernate:
      ddl-auto: ${APP_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: ${APP_DEFAULT_SCHEMA}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

#oidc...
http.proxy.parametername: notused

no.nav.security.jwt:
  expirythreshold: 60 #threshold in minutes until token expires
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}
      proxyurl: ${APP_AZURE_PROXY_URL}

springdoc:
  packages-to-scan: "no.nav.familie.ba.infotrygd"
  paths-to-match: "/infotrygd/**"
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${AZURE_APP_CLIENT_ID}
      scope-separator: ","
    disable-swagger-default-url: true

# Swagger
AUTHORIZATION_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/authorize
TOKEN_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token
API_SCOPE: api://${AZURE_APP_CLIENT_ID}/.default

TEAMFAMILIE_FORVALTNING_GROUP_ID: "928636f4-fd0d-4149-978e-a6fb68bb19de"