server.port: 8080

spring:
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    platform: ${APP_DATASOURCE_PLATFORM}
    driver-class-name: ${APP_DATASOURCE_DRIVER}
  jpa:
    # For Oracle: database-platform: org.hibernate.dialect.Oracle10gDialect
    database-platform: ${APP_JPA_PLATFORM}
    hibernate:
      ddl-auto: ${APP_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: ${APP_DEFAULT_SCHEMA}

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

#oidc...
http.proxy.parametername: notused

no.nav.security.oidc.issuer:
  azure:
    discoveryurl: ${APP_DISCOVERY_URL}
    accepted_audience: ${APP_AUD}
    proxyurl: ${APP_PROXY_URL}

app:
  security:
    issuer: ${APP_CLIENT_ISSUER}
    clientWhitelist: ${APP_CLIENT_WHITELIST}