version: 2.1

orbs:
  nais: navikt/nais-deployment@1.5.0

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/app

jobs:
  build:
    executor: openjdk
    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle --scan build
      - run: echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)-$CIRCLE_BUILD_NUM" > .version
      - persist_to_workspace:
          root: /home/circleci/app
          paths:
            - .version
      - nais/docker-deploy:
          registry: docker.pkg.github.com
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/beregningsgrunnlag
          tag: $(cat .version)

  dev-deploy:
    executor: nais/go-executor
    steps:
      - nais-deploy:
          environment: dev-fss
  prod-deploy:
    executor: nais/go-executor
    steps:
      - nais-deploy:
          environment: prod-fss

commands:
  nais-deploy:
    parameters:
      environment:
        type: string
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - nais/generate-nais-deployment:
            repo: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
            image: docker.pkg.github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/beregningsgrunnlag
            tag: $(cat ~/app/.version)
            github-app-id: 34242
            nais-template: nais/<< parameters.environment >>.yml
            environment: << parameters.environment >>
            team: infotrygd

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /dev-.*/
      - dev-deploy:
          filters:
            branches:
              only:
                - master
                - /dev-.*/
          requires:
            - build
      - prod-deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - dev-deploy
