apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-infotrygd
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8080 # Required. The port number which is exposed by the container and should receive HTTP traffic.
  liveness: # HTTP endpoint that signals 200 OK when the application is running.
    path: /actuator/health
    initialDelay: 30
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
      # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness: # HTTP endpoint that signals 200 OK when it is okay to start routing traffic to the application.
    path: /actuator/health
    # /rest/internal/isAlive
    initialDelay: 30
    timeout: 1
  replicas: # Optional. Set min = max to disable autoscaling.
    min: 2 # minimum number of replicas.
    max: 2 # maximum number of replicas.
  leaderElection: true
  # Compare this value with the $HOSTNAME to see if the current instance is the leader
  preStopHookPath: "" # Optional. A HTTP GET will be issued to this endpoint at least once before the pod is terminated.
  # See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  prometheus: # Optional.
    enabled: true # if true the pod will be scraped for metrics by prometheus
    path: /actuator/prometheus # Path to prometheus-metrics
    # /actuator/prometheus
  istio: # Optional.
    enabled: false # Optional. When true, envoy-proxy sidecar will be injected into pod and https urls envvars will be rewritten
  resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
    limits:
      memory: 2048Mi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: 500m
      memory: 1024Mi
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - "https://familie-ba-infotrygd.dev.intern.nav.no/"
    - "https://familie-ba-infotrygd.dev-fss-pub.nais.io"
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  secureLogs:
    enabled: true
  vault:
    enabled: true # Optional. If set to true fetch secrets from Secret Service and inject into the pods. todo link to doc.
    paths:
      - kvPath: /oracle/data/dev/creds/ba_infotrygd_q1-user
        mountPath: /var/run/secrets/oracle/creds
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-baks-mottak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-ba-migrering
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-ba-sak-lokal
          namespace: teamfamilie
          cluster: dev-fss
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b # teamfamilie-forvaltning
          - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-ba-infotrygd.dev.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  env:
    - name: APP_DATASOURCE_URL
      value: jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/infotrygd_baq
    - name: APP_DATASOURCE_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DATASOURCE_DRIVER
      value: oracle.jdbc.driver.OracleDriver
    - name: APP_JPA_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DEFAULT_SCHEMA
      value: INFOTRYGD_BAQ
    - name: APP_DDL_AUTO
      value: none
    - name: APP_AZURE_PROXY_URL
      value: https://webproxy-nais.nav.no:8088
    - name: APP_CLIENT_WHITELIST
      value: azure/146ccc69-7cd0-4b8e-86a5-144534e53a00,azure/288f2ef5-23fa-4fc5-af6b-6001adaf9e50,azure/e50c7d59-7183-4978-8d8c-8af7f9a7e6a9,azure/1ded84b0-21b7-4042-9c84-820c939021a6,azure/dc2b8dca-9de9-42f7-9103-f52a9169428e,azure/a38ae9cf-f55a-480a-b830-cc68d53f8445,azure/b5b51c6e-aa53-4ab8-ae68-f7aed5ae4b1d
    - name: APP_DATASOURCE_USERNAME_PATH
      value: /var/run/secrets/oracle/creds/username
    - name: APP_DATASOURCE_PASSWORD_PATH
      value: /var/run/secrets/oracle/creds/password
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JAVA_OPTS
      value: "-XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError"
