apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-infotrygd
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8080 # Required. The port number which is exposed by the container and should receive HTTP traffic.
  liveness: # HTTP endpoint that signals 200 OK when the application is running.
    path: /actuator/health
    initialDelay: 120
    timeout: 1
    periodSeconds: 5     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
      # nais will try failureThreshold times before giving up and restarting the Pod
    # Defaults to 3
  readiness: # HTTP endpoint that signals 200 OK when it is okay to start routing traffic to the application.
    path: /actuator/health
    # /rest/internal/isAlive
    initialDelay: 120
    timeout: 1
  replicas: # Optional. Set min = max to disable autoscaling.
    min: 2 # minimum number of replicas.
    max: 2 # maximum number of replicas.
    cpuThresholdPercentage: 50 # total cpu percentage threshold on deployment, at which point it will increase number of pods if current < max
  leaderElection: true # Optional. If true, a http endpoint will be available at $ELECTOR_PATH that return the current leader
  # Compare this value with the $HOSTNAME to see if the current instance is the leader
  preStopHookPath: "" # Optional. A HTTP GET will be issued to this endpoint at least once before the pod is terminated.
  # See https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  prometheus: # Optional.
    enabled: true # if true the pod will be scraped for metrics by prometheus
    path: /actuator/prometheus # Path to prometheus-metrics
    # /actuator/prometheus
  istio: # Optional.
    enabled: false # Optional. When true, envoy-proxy sidecar will be injected into pod and https urls envvars will be rewritten
  resources: # Optional. See: http://kubernetes.io/docs/user-guide/compute-resources/
    limits:
      cpu: 1500m # app will have its cpu usage throttled if exceeding this limit
      memory: 2048Mi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
      cpu: 500m
      memory: 1024Mi
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - "https://familie-ba-infotrygd.nais.adeo.no"
    - "https://familie-ba-infotrygd.intern.nav.no"
    - "https://familie-ba-infotrygd.prod-fss-pub.nais.io"
  logformat: accesslog # Optional. The format of the logs from the container if the logs should be handled differently than plain text or json
  logtransform: dns_loglevel # Optional. The transformation of the logs, if they should be handled differently than plain text or json
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/ba_infotrygd_p-user
        mountPath: /var/run/secrets/oracle/creds
  accessPolicy:
    inbound:
      rules:
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-ba-mottak
          namespace: teamfamilie
          cluster: prod-fss
        - application: familie-ba-migrering
          namespace: teamfamilie
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: 3d718ae5-f25e-47a4-b4b3-084a97604c1d # teamfamilie-forvaltning
          - id: 87190cf3-b278-457d-8ab7-1a5c55a9edd7 # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 tilgang til prosessering
      replyURLs:
        - "https://familie-ba-infotrygd.nais.adeo.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  env:
    - name: APP_DATASOURCE_URL
      value: jdbc:oracle:thin:@a01dbfl037.adeo.no:1521/infotrygd_bap
    - name: APP_DATASOURCE_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DATASOURCE_DRIVER
      value: oracle.jdbc.driver.OracleDriver
    - name: APP_JPA_PLATFORM
      value: org.hibernate.dialect.Oracle10gDialect
    - name: APP_DEFAULT_SCHEMA
      value: INFOTRYGD_BAP
    - name: APP_DDL_AUTO
      value: none
    - name: APP_AZURE_PROXY_URL
      value: https://webproxy-nais.nav.no:8088
    - name: APP_CLIENT_WHITELIST
      value: azure/0412f3eb-b22a-4d3f-99aa-319321eb340f,azure/984d4731-b95d-4f87-8154-d8f153f0ebee,azure/a1e0a7ad-7838-41c4-bf64-84b689d569e9,azure/f1fe85a0-704b-42e9-bd1e-5793be962010,azure/bc8e9286-2696-416d-b658-522301569562
    - name: APP_DATASOURCE_USERNAME_PATH
      value: /var/run/secrets/oracle/creds/username
    - name: APP_DATASOURCE_PASSWORD_PATH
      value: /var/run/secrets/oracle/creds/password
    - name: SPRING_PROFILES_ACTIVE
      value: prod
