name: Build-Deploy-Prod
on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/navikt/familie-ba-infotrygd:${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-ba-infotrygd:latest
jobs:
  deploy-to-prod:
    name: Bygg app/image, push til github, deploy til prod-fss og dev-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Test and build
        env: 
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test build
      - name: Build docker image
        run: |
          docker build -t $IMAGE -t ${IMAGE_LATEST} .
      - name: Check API rate limit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s "https://api.github.com/rate_limit" -H "Authorization: token $GITHUB_TOKEN"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${IMAGE}
          docker push ${IMAGE_LATEST}
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
      - name: Deploy to prod-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/prod-fss.yml