name: PR build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: test and build
        run: ./gradlew test build
      - name: build docker image
        run: docker build . --pull
