name: Build-Deploy-Preprod

on:
  workflow_dispatch:
  pull_request:

env:
  IMAGE: ghcr.io/navikt/familie-ba-infotrygd:${{ github.sha }}
jobs:
  deploy-to-dev:
    name: Bygg app/image, push til github, deploy til dev-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test build
      - name: Build docker image
        run: |
          docker build -t $IMAGE .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${IMAGE}
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
