name: Build-Deploy-Preprod

on:
  workflow_dispatch:
  pull_request:


jobs:
  deploy-to-dev:
    name: Bygg app/image, push til github, deploy til dev-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test build
      - uses: nais/docker-build-push@v0
        id: docker-push
        if: github.triggering_actor != 'dependabot[bot]'
        with:
          team: teamfamilie
          push_image: true
          dockerfile: Dockerfile
          docker_context: .
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/bom.json
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v2
        if: github.triggering_actor != 'dependabot[bot]'
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
          VAR: image=${{ steps.docker-push.outputs.image }}
