name: Build-Deploy-Preprod

on:
  workflow_dispatch:
  pull_request:

env:
  IMAGE: ghcr.io/navikt/familie-ba-infotrygd:${{ github.sha }}
jobs:
  deploy-to-dev:
    name: Bygg app/image, push til github, deploy til dev-fss
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Test and build
        env:
          GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew test build
      - name: Build docker image
        run: |
          docker build -t $IMAGE .
      - name: Push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
      - name: Deploy to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
